In [1]:
import numpy as np

In [2]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
a = a * 5
print(a)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [4]:
b = np.identity(5) /5
print(b)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


In [5]:
a * b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
c = np.array([[1,2,3],[4,0,6],[7,8,9]])
np.linalg.det(c)

59.999999999999986

In [7]:
np.linalg.inv(c)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [18]:
np.linalg.matrix_rank(np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]))

1

In [11]:
a = [[1,5],[4,8],[7,5]]
b = [2,8,3]
np.dot(b,a)

array([55, 89])

In [12]:
a, b, c = [1,5,0],[2,8,7],[7,1.5,3]
v = np.cross(a,b)
p = np.inner(v,c)
print(p)

228.5
